Create single player flow and layout game and battle pages, add some features to game item button.
dg1886/rps_game pull request #12
Opened 2022-06-16 09:39 UTC by dg1886

2022-06-17 10:48 UTC, neko-peko requested changes

2022-06-17 10:48 UTC, neko-peko commented on src/components/ResultMessage/index.js
> +      {condition
Не лучше ли будет написать отдельный маленький ретурн?
```if (!condition) return null;```

Он будет читабельнее, на мой взгляд

2022-06-17 10:48 UTC, neko-peko commented on src/pages/single_player/Battle/index.js
> +  const result = () => {
Представляю, что будет, если добавить ещё элментов, кроме КМН )))
В таких случаях лучше использовать матрицу. Вот простая, накидал за 5 минут:
```
// Или можете хранить другим способом
const rps = {
    ROCK: 0,
    PAPER: 1,
    SCISSORS: 2
}

const winMatrix = [
    [0, -1, 1],
    [1, 0, -1],
    [-1, 1, 0]
]

/* 
* @playerChoice - rpc key ('ROCK')
* @computerChoice - rpc key ('PAPER')
*/
const getWinPoints = (playerChoice, computerChoice) => winMatrix[rpc[playerChoice]][rpc[computerChoice]];
```

2022-06-17 10:48 UTC, neko-peko commented on src/pages/single_player/Battle/index.js
> +    const timer = counter > 0 ? setInterval(() => {
Тогда уж лучше таймаут. 
Обновил стейт -> задел депенденси -> поставил новый таймаут. Таймаут отрабатывает только один раз.
Это хорошо, что на каждый ререндер сбрасывается интервал. Но это не страхует тебя от выстрела себе в ногу.

2022-06-17 10:48 UTC, neko-peko commented on src/pages/single_player/Battle/index.js
> +            <PaperImage />
Зачем копипастить постоянно? Держите код DRY

```
const choiceIcons = {
  [GAME_ITEMS.PAPER]: <PaperImage />,
  [GAME_ITEMS.ROCK]: <RockImage />,
  [GAME_ITEMS.SCISSORS]: <ScissorsImage />
}

const ChoiceButton = ({myChoice}) => (
  <IconButton isWin={win} variant="iconWrapXl" figure="rock">
    {choiceIcons[myChoice]}
  </IconButton>
)
```

2022-06-17 10:48 UTC, neko-peko commented on src/pages/single_player/Battle/index.js
> +        <ResultMessage condition={draw} firstValue="Draw" />
Это тоже можно переписать на один компонент, который принимает в себя только результат (0, 1, -1 или D, W, L или draw, win, lose) и сам разберётся, что ему выводить. Это его единственная ответственность и он должен это делать максимально сам. Иначе какой смысл в condition если ты просто пихаешь в компонент две строки. Если убрать condition, то можно просто не выводить вторую строку, если её нет. Результат был бы точно такой же. Но это такое себе
```
// condition = 1 = win = W
<ResultMessage condition={condition} />
```

2022-06-17 10:48 UTC, neko-peko commented on src/pages/single_player/Battle/index.js
> +              {house === GAME_ITEMS.PAPER && (
аналогично предыдущему комменту про DRY

2022-06-17 10:48 UTC, neko-peko commented on src/pages/single_player/Menu/index.jsx
> +        <Box
Такая же фигня. Неужели вам в кайф копипастить, а потом смотреть по этой портянке, что вы не забыли поменять?) 
Сделайте лучше нормальные функции-фабрики.

2022-06-22 14:25 UTC, dg1886 commented on src/pages/single_player/Menu/index.jsx
> +        <Box
Не уверен что правильно понял про функции-фабрики.

2022-06-22 15:17 UTC, neko-peko commented on src/components/ChoiceButton/index.js
> +  };
winAnimation можно сделать чистой функцией, вынеся её из компоненты и прокинув просто 2 аргумента.

2022-06-22 15:24 UTC, neko-peko commented on src/components/ChoiceButton/index.js
> +};
Дублирование, как в MenuButton.
Лучше будет, если вы будете использовать тут `GAME_ITEMS` из констант вместо `RPC` и руководствоваться названиями, а не цифрами.

2022-06-22 15:24 UTC, neko-peko commented on src/components/MenuButton/index.js
> +};
Дубль.
Тут так же лучше заюзать `GAME_ITEMS` вместо `RPC`

2022-06-22 15:26 UTC, neko-peko commented on src/components/MenuButton/index.js
> +    setMyChoice(Number(e.currentTarget.id));
Из-за `GAME_ITEMS` тут будет прокидываться просто строка ("ROCK" например).

2022-06-22 15:55 UTC, neko-peko commented on src/services/gameContext.js
> +    setComputerChoice(Math.floor(Math.random() * 3));
Что такое `3`? Тут просто ошибиться и не найти это место при изменениях.
```setComputerChoice(Math.floor(Math.random() * Object.keys(GAME_ITEMS).length ));```

2022-06-24 06:43 UTC, merged